{% set name = "attributes-doc" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/attributes-doc-{{ version }}.tar.gz
  sha256: b1576c94a714e9fc2c65c47cf10d0c8e1a5f7c4f5ae7f69006be108d95cbfbfb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - attributes_doc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tkukushkin/attributes-doc
  summary: PEP 224 implementation
  dev_url: https://github.com/tkukushkin/attributes-doc
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - abrahammurciano
